import {
  AdminLogEntity,
  BattleRecordEntity,
  DailyGoalProgressEntity,
  DungeonProgressEntity,
  FriendAssistRecordEntity,
  FriendshipEntity,
  GachaRecordEntity,
  GameConfigEntity,
  GuildContributionEntity,
  GuildEntity,
  GuildMemberEntity,
  IdleClaimEntity,
  IdleSessionEntity,
  InventoryItemEntity,
  MailEntity,
  PlayerCharacterEntity,
  PlayerEntity,
  RankingEntryEntity,
  UserEntity,
} from './entities';

export const gameEntities = [
  AdminLogEntity,
  BattleRecordEntity,
  DailyGoalProgressEntity,
  DungeonProgressEntity,
  FriendAssistRecordEntity,
  FriendshipEntity,
  GachaRecordEntity,
  GameConfigEntity,
  GuildContributionEntity,
  GuildEntity,
  GuildMemberEntity,
  IdleClaimEntity,
  IdleSessionEntity,
  InventoryItemEntity,
  MailEntity,
  PlayerCharacterEntity,
  PlayerEntity,
  RankingEntryEntity,
  UserEntity,
];
