export const CURRENT_SCHEMA_VERSION = 'ConcurrentMutationSafety1788509000000';
export const INITIAL_SCHEMA_TIMESTAMP = 1788502608304;

export const REQUIRED_GAME_TABLES = [
  'admin_logs',
  'battle_records',
  'daily_goal_progress',
  'dungeon_progress',
  'friend_assist_records',
  'friendships',
  'gacha_records',
  'game_configs',
  'guild_contributions',
  'guild_members',
  'guilds',
  'idle_claims',
  'idle_sessions',
  'inventory_items',
  'mails',
  'player_characters',
  'players',
  'ranking_entries',
  'users',
] as const;

export const REQUIRED_CORE_COLUMNS: Record<string, string[]> = {
  users: ['id', 'accountId', 'provider', 'passwordHash', 'status', 'metadata', 'createdAt', 'updatedAt'],
  players: ['id', 'userId', 'displayName', 'level', 'exp', 'gold', 'flags', 'createdAt', 'updatedAt'],
  player_characters: [
    'id',
    'playerId',
    'characterConfigId',
    'attributeType',
    'professionType',
    'level',
    'exp',
    'skillSlots',
    'equipment',
    'createdAt',
    'updatedAt',
  ],
  inventory_items: [
    'id',
    'playerId',
    'itemConfigId',
    'itemType',
    'quantity',
    'locked',
    'payload',
    'createdAt',
    'updatedAt',
  ],
  battle_records: [
    'id',
    'playerId',
    'dungeonId',
    'success',
    'duration',
    'damageScore',
    'characterIds',
    'rewards',
    'resultPayload',
    'createdAt',
  ],
};
